steps:
  # Build frontend
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: '.'
    
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: '.'

  # Upload frontend to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-d', 'dist/', 'gs://music-game-static/']

  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/music-game-api:$COMMIT_SHA', './server']
    dir: 'server'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/music-game-api:$COMMIT_SHA']

  # Deploy to Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - music-game-instance
      - --zone=us-central1-a
      - --command=sudo docker pull gcr.io/$PROJECT_ID/music-game-api:$COMMIT_SHA && sudo docker stop music-game-api || true && sudo docker rm music-game-api || true && sudo docker run -d --name music-game-api --restart unless-stopped -p 8080:8080 --env-file /etc/music-game/.env gcr.io/$PROJECT_ID/music-game-api:$COMMIT_SHA

images:
  - 'gcr.io/$PROJECT_ID/music-game-api:$COMMIT_SHA'